services:
  postgresql-kotlin-bookstore:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aadi #Secure it during production
    volumes:
      - ./docker/postgres/data:/data/postgres
    networks:
      - kotlin-bookstore-network
  pgadmin-kotlin-bookstore:
    container_name: pgadmin-kotlin-bookstore
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bookstore.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./docker/pgadmin/data:/data/pgadmin
    ports:
      - "5050:80"
    networks:
      - kotlin-bookstore-network
    depends_on:
      - postgresql-kotlin-bookstore
    restart: unless-stopped
networks:
  kotlin-bookstore-network:
    driver: bridge